package:
  name: rdkit-postgresql
  version: 2015.03.1

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_tag: Release_2015_03_1 
  patches:
    - Makefile.patch
    - adapter.cpp.patch

build:
  number: 0

requirements:
  build:
    - rdkit 2015.03.1
    - postgresql >=9.4,<9.5
  run:
    - rdkit 2015.03.1
    - postgresql >=9.4,<9.5

about:
  home: http://rdkit.org
  license: BSD
