package:
  name: rdkit-postgresql
  version: 2014.03.1

source:
  fn: Release_2014_03_1.zip
  url: https://github.com/rdkit/rdkit/archive/Release_2014_03_1.zip
  patches:
    - Makefile.patch
    - adapter.cpp.patch

build:
  number: 1

requirements:
  build:
    - rdkit 2014.03.1
    - postgresql
  run:
    - rdkit 2014.03.1
    - postgresql

about:
  home: http://rdkit.org
  license: BSD
