package:
  name: rdkit-postgresql
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_tag: Release_2015_09_2
  patches:
    - Makefile.patch
    - adapter.cpp.patch

build:
  number: 0

requirements:
  build:
    - python
    - rdkit 2015.09.2
    - postgresql >=9.4,<9.5
  run:
    - python
    - rdkit 2015.09.2
    - postgresql >=9.4,<9.5

about:
  home: http://rdkit.org
  license: BSD
