package:
  name: rdkit-postgresql
  version: 2014.09.1pre

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_branch: master
  patches:
    - Makefile.patch
    - adapter.cpp.patch

build:
  number: 0

requirements:
  build:
    - rdkit 2014.09.1pre
    - postgresql
  run:
    - rdkit 2014.09.1pre
    - postgresql

about:
  home: http://rdkit.org
  license: BSD
