package:
  name: django-rdkit
  version: 0.0.4

source:
  git_url: https://github.com/rdkit/django-rdkit.git
  git_tag: v0.0.4

build:
  number: 0

requirements:
  build:
    - python
    - rdkit-postgresql
    - psycopg2
    - django >=1.8
  run:
    - python
    - rdkit-postgresql
    - psycopg2
    - django >=1.8

about:
  license: BSD
