package:
  name: rdkit-postgresql95
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: Release_2017_03_1
  patches:
    - cmakelists.txt.patch
    - adapter.cpp.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - postgresql >=9.5
    - rdkit >=2017.03
  run:
    - postgresql >=9.5

about:
  home: http://rdkit.org
  license: BSD
