package:
  name: rdkit
  # version is the last TAG + the number of commits since
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: https://github.com/rdkit/rdkit.git
  # Can pull master for development
  git_rev: modern_cxx
  patches:
    - rdpaths.patch
    - rdconfig.patch [win]

build:
  number: 1

requirements:
  build:
    - requests
    - gxx_linux-64 [linux]
    - boost-cpp ==1.65.1 [unix]
    - boost ==1.65.1 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.59.0 [win and py35]
    - boost ==1.59.0 [win and py36]
    - python
    - numpy ==1.12
    - pillow
    - freetype
    - nox
    - cairo_nox [unix]
    - pkg-config [unix]
    - eigen
    - pandas
    - m2-patch [win]
  run:
    - boost ==1.65.1 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.59.0 [win and py35]
    - boost ==1.59.0 [win and py36]
    - cairo [unix]
    - python 
    - pillow
    - pandas
    - numpy >=1.12
test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
