package:
  name: rdkit
  version: 2014.09.2

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_tag: Release_2014_09_2
  patches:
    - rdpaths.patch

build:
  number: 0 

requirements:
  build:
    - cmake [linux]
    - cmake <=2.8.9 [osx]
    - requests
    - python
    - boost
    - numpy
    - pil [py2k]
    - pillow [py3k]
    - freetype
    - py2cairo [linux and py2k]
  run:
    - boost
    - python
    - numpy

test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
