package:
  name: postgresql95
  version: 9.5.10

source:
  fn: postgresql-9.5.10.tar.bz2
  url: https://ftp.postgresql.org/pub/source/v9.5.10/postgresql-9.5.10.tar.bz2
  md5: a21527830bf6b62f4b33c24ef708f5be 
  patches:
    - prefer_ncurses_to_termcap.patch [not win]

build:
  number: 0

requirements:
  build:
    - perl [win]
    - gettext [win]
    - zlib
    - openssl
    - ncurses 6.0 [not win]
    - readline [not win]
    - libxml2
    - libxslt
  run:
    - openssl
    - ncurses 6.0 [not win]
    - readline [not win]
    - libxml2
    - libxslt

test:
  commands:
    - initdb --help
    - postgres --help
    - createdb --help
    - psql --help

about:
  home: http://www.postgresql.org
  license: PostgreSQL License

