steps:
- bash: |
    source ${CONDA}/etc/profile.d/conda.sh
    sudo chown -R ${USER} ${CONDA}
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda install conda-build
  displayName: Setup build environment
- bash: |
    source ${CONDA}/etc/profile.d/conda.sh
    export CONDA_PY=${PYTHON_VERSION}
    conda build rdkit
  displayName: Do conda build and test
- bash: |
    mkdir -p $(System.DefaultWorkingDirectory)/distrib/linux-64
    cp /usr/share/miniconda/conda-bld/linux-64/rdkit* $(System.DefaultWorkingDirectory)/distrib/linux-64
  displayName: Create build artifacts
- publish: $(System.DefaultWorkingDirectory)/distrib 
  artifact: conda_build_rdkit_linux_$(python.version)

