steps:
- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Setup windows path
- script: |
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda install conda-build
  displayName: Setup build environment
- bash: |
    export CONDA_PY=${PYTHON_VERSION}
    sed -i 's/git_rev: Release_2020_03/git_rev: master/; s/^  version:/# version;/; s/# nightly version:/version:/' rdkit/meta.yaml
    conda build rdkit
  displayName: Do conda build and test
- bash: |
    mkdir -p $(System.DefaultWorkingDirectory)/distrib/win-64
    echo "-----------------"
    ls -l /usr/local/miniconda/conda-bld/osx-64
    cp /usr/local/miniconda/conda-bld/osx-64/rdkit* $(System.DefaultWorkingDirectory)/distrib/win-64
  displayName: Create build artifacts
- publish: $(System.DefaultWorkingDirectory)/distrib 
  artifact: conda_build_rdkit_osx_$(python.version)

